modLoader = "kotlinforforge"

loaderVersion = "[4,)" # the loader is kotlin for forge
license = "AGPL-3.0"
issueTrackerURL = "https://github.com/{githubUser}/{githubRepo}/issues"

[[mods]]
modId = "petphraseplus2"
version = "1.0.0"
displayName = "PetPhrasePlus2"
authors = "WolfGenerals"
description = ""
updateJSONURL="https://raw.githubusercontent.com/WolfGenerals/PetPhrasePlus2/main/updates.json"
logoFile="assets/petphraseplus2/icon.png"
[[dependencies.petphraseplus2]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.petphraseplus2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"
